documentation edits
HigherOrderCO/Bend pull request #394
Opened 2024-05-19 03:35 UTC by jasonlmfong

2024-05-19 17:51 UTC, Landixbtw commented
Grammar police

2024-05-20 07:51 UTC, developedby requested changes
I think there a lot of places that refer to entry points as entrypoints haha

2024-05-20 07:51 UTC, developedby commented on docs/writing-fusing-functions.md
> +This is how a `Not` function that acts on this encoding can be defined.
```suggestion
This is how a `Not` function that acts on this encoding can be defined:
```

2024-05-20 07:51 UTC, developedby approved these changes

2024-05-20 07:52 UTC, developedby approved these changes

2024-05-20 08:31 UTC, developedby commented
Looks like something changed in the tests earlier. I'll merge this after I fix it

2024-05-20 17:19 UTC, developedby commented
I've moved to #415 to fix the merge and add some other similar things.

2024-05-20 17:19 UTC, closed without merging

2024-05-20 17:21 UTC, jasonlmfong commented
Sounds good thanks