Refactor Transform String Resugar Term Scott with visitor pattern and improved error handling
HigherOrderCO/Bend pull request #714
Opened 2024-09-11 15:03 UTC by Liberxue

#713 
* Introduce  trait, allowing definition of visitors for different Term processing logics.
* Create  struct to wrap user-provided cons handling functions, implementing the  trait.
* Implement  struct to handle default cons patterns, also implementing the  trait.
* Replace  with  type, better expressing success or failure semantics.
* Utilize Rust's pattern matching and  method to simplify error handling process.

2024-09-11 15:19 UTC, developedby requested changes
The visitor is completely unnecessary here, doesn't really simplify.

I like the idea of the `try_resugar` functions, it lets the pattern matching not be repeated twice.

You could have a single `build_string` function that takes takes the encoding, tries the correct encoded pattern and tries the non-applied constructors, without repetition.

Also, please leave the `if` tree since it mimics the shape of the AST and is easier for me to visualize the structure.

2024-09-11 16:54 UTC, Liberxue commented
> The visitor is completely unnecessary here, doesn't really simplify.
> 
> I like the idea of the `try_resugar` functions, it lets the pattern matching not be repeated twice.
> 
> You could have a single `build_string` function that takes takes the encoding, tries the correct encoded pattern and tries the non-applied constructors, without repetition.
> 
> Also, please leave the `if` tree since it mimics the shape of the AST and is easier for me to visualize the structure.

Done Please review～～thx @developedby

2024-09-11 17:04 UTC, developedby requested changes
This is nicer to read without the visitor, but my other previous comments still apply.

Also, please do the changes on `resugar_list` as well. It's almost an exact copy of this one, just looking for a slightly different pattern. It would be confusing if they were implemented differently

2024-09-11 17:04 UTC, developedby commented on src/fun/transform/resugar_string.rs
> +        if let Term::Lam { tag: Tag::Static, pat, bod } = current {
This is specifically the "num-scott" encoding, you shouldn't apply it for all cases

2024-09-12 13:44 UTC, Liberxue commented
> This is nicer to read without the visitor, but my other previous comments still apply.
> 
> Also, please do the changes on `resugar_list` as well. It's almost an exact copy of this one, just looking for a slightly different pattern. It would be confusing if they were implemented differently

In the `resugar_lists` file, after careful reading, I found that extracting code blocks could lead to reduced performance due to cloning. I haven't thought of a better approach at the moment~~~

2024-09-17 13:12 UTC, developedby approved these changes

2024-09-17 13:13 UTC, developedby commented on src/fun/transform/resugar_list.rs
> +      // Searc      h for a List/Cons pattern in the term and try to build a list from that point on.
```suggestion
      // Search for a List/Cons pattern in the term and try to build a list from that point on.
```

2024-09-17 13:33 UTC, developedby commented
Can you just run `cargo fmt`?

2024-09-17 14:17 UTC, Liberxue commented
> Can you just run `cargo fmt`?
So Sorry OKK~~ done

2024-09-17 15:44 UTC, developedby commented
Thank you very much for the contribution

2024-09-17 15:47 UTC, merged